sudo: required
services:
  - docker

before_install:
  - docker build -t pierremilvue/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pierremilvue/react-test npm test

after_success:
  - docker build -t pierremilvue/multi-client ./client
  - docker build -t pierremilvue/multi-nginx ./nginx
  - docker build -t pierremilvue/multi-server ./server
  - docker build -t pierremilvue/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pierremilvue/multi-client
  - docker push pierremilvue/multi-nginx
  - docker push pierremilvue/multi-server
  - docker push pierremilvue/multi-worker